apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-jskv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-rhtap-devfile-multi-component-jskv
    app.kubernetes.io/part-of: mc-two-scenarios
  name: devfile-sample-python-basic-rhtap-devfile-multi-component-jskv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-jskv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-jskv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vbgl-tenant/mc-two-scenarios/devfile-sample-python-basic-rhtap-devfile-multi-component-jskv@sha256:32f5dd18bd0cbd0f3c036a9562cdc90626f8f840b66a4b3a548e19816a11e6dc
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
